// Export all schemas
export * from './auth';
export * from './community';
export * from './course';
export * from './enrollment';
export * from './quiz';
export * from './scoreboard';
export * from './uploads';
export * from './posts';
export * from './comments';